# 由PNCconf在Sat Mar  7 10:06:44 2026生成
# 使用的 LinuxCNC 版本:  Master (2.9)
# 如果您对此文件进行了更改，那么
# 再次运行PNCconf时会被覆盖

[EMC]
MACHINE = F7I92_V2.0
DEBUG = 0
VERSION = 1.1

[DISPLAY]
DISPLAY = gmoccapy
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = ACTUAL
MAX_FEED_OVERRIDE = 2.000000
MAX_SPINDLE_OVERRIDE = 1.000000
MIN_SPINDLE_OVERRIDE = 0.500000
INTRO_GRAPHIC = linuxcnc.gif
INTRO_TIME = 5
PROGRAM_PREFIX = /home/lite/linuxcnc/nc_files
INCREMENTS = 5mm 1mm .5mm .1mm .05mm .01mm .005mm
POSITION_FEEDBACK = ACTUAL
DEFAULT_LINEAR_VELOCITY = 600.000000
MAX_LINEAR_VELOCITY = 25.000000
MIN_LINEAR_VELOCITY = 0.500000
DEFAULT_ANGULAR_VELOCITY = 1200.000000
MAX_ANGULAR_VELOCITY = 1200
MIN_ANGULAR_VELOCITY = 1000
EDITOR = gedit
GEOMETRY = xyz
CYCLE_TIME = 100

[FILTER]
PROGRAM_EXTENSION = .png,.gif,.jpg Greyscale Depth Image
PROGRAM_EXTENSION = .py Python Script
png = image-to-gcode
gif = image-to-gcode
jpg = image-to-gcode
py = python

[TASK]
TASK = milltask
CYCLE_TIME = 0.010

[RS274NGC]
PARAMETER_FILE = linuxcnc.var
RS274NGC_STARTUP_CODE = G21 G40 G90 G94 G97 G64 P0.025

[EMCMOT]
EMCMOT = motmod
COMM_TIMEOUT = 1.0
SERVO_PERIOD = 1000000

[HMOT]
# **** 仅供参考 ****
CARD0=hm2_7i92.0

[HAL]
HALUI = halui
HALFILE = F7I92_V2.0.hal
HALFILE = mpg.hal
HALFILE = custom.hal
POSTGUI_HALFILE = gmoccapy_postgui.hal
POSTGUI_HALFILE = custom_postgui.hal
SHUTDOWN = shutdown.hal

[HALUI]

[KINS]
JOINTS = 5
KINEMATICS = xyzac-trt-kins sparm=identityfirst

[TRAJ]
COORDINATES =  XYZAC
MAX_ANGULAR_VELOCITY = 360.00
DEFAULT_ANGULAR_VELOCITY = 36.00
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
DEFAULT_LINEAR_VELOCITY = 250
MAX_LINEAR_VELOCITY = 25.00

[EMCIO]
EMCIO = io
CYCLE_TIME = 0.100
TOOL_TABLE = tool.tbl

#******************************************
[AXIS_X]
MAX_VELOCITY = 25.0
MAX_ACCELERATION = 750.0
MIN_LIMIT = -2000
MAX_LIMIT = 2000.0

[JOINT_0]
TYPE = LINEAR
HOME = 0.0
FERROR = 10.0
MIN_FERROR = 1.0
MAX_VELOCITY = 25.0
MAX_ACCELERATION = 750.0
# 以下值应该比最大速度与最大加速度高25%
# 如果使用背隙补偿 STEPGEN_MAXACCEL 应该比原本大100%。
STEPGEN_MAXVEL = 31.25
STEPGEN_MAXACCEL = 937.50
P = 1000.0
I = 0.0
D = 0.0
FF0 = 0.0
FF1 = 1.0
FF2 = 0.0
BIAS = 0.0
DEADBAND = 0.0
MAX_OUTPUT = 0.0
#这些以纳秒为单位
DIRSETUP   = 10000
DIRHOLD    = 10000
STEPLEN    = 5000
STEPSPACE  = 5000
STEP_SCALE = 200.0
MIN_LIMIT = -2000
MAX_LIMIT = 2000.0
HOME_OFFSET = 0.0
HOME_SEQUENCE = 2
#******************************************

#******************************************
[AXIS_Y]
MAX_VELOCITY = 25.0
MAX_ACCELERATION = 750.0
MIN_LIMIT = -2000
MAX_LIMIT = 2000.0

[JOINT_1]
TYPE = LINEAR
HOME = 0.0
FERROR = 10.0
MIN_FERROR = 1.0
MAX_VELOCITY = 25.0
MAX_ACCELERATION = 750.0
# 以下值应该比最大速度与最大加速度高25%
# 如果使用背隙补偿 STEPGEN_MAXACCEL 应该比原本大100%。
STEPGEN_MAXVEL = 31.25
STEPGEN_MAXACCEL = 937.50
P = 1000.0
I = 0.0
D = 0.0
FF0 = 0.0
FF1 = 1.0
FF2 = 0.0
BIAS = 0.0
DEADBAND = 0.0
MAX_OUTPUT = 0.0
#这些以纳秒为单位
DIRSETUP   = 10000
DIRHOLD    = 10000
STEPLEN    = 5000
STEPSPACE  = 5000
STEP_SCALE = 200.0
MIN_LIMIT = -2000
MAX_LIMIT = 2000.0
HOME_OFFSET = 0.0
HOME_SEQUENCE = 3
#******************************************

#******************************************
[AXIS_Z]
MAX_VELOCITY = 25.0
MAX_ACCELERATION = 750.0
MIN_LIMIT = -1000.0
MAX_LIMIT = 1000

[JOINT_2]
TYPE = LINEAR
HOME = 0.0
FERROR = 10.0
MIN_FERROR = 1.0
MAX_VELOCITY = 25.0
MAX_ACCELERATION = 750.0
# 以下值应该比最大速度与最大加速度高25%
# 如果使用背隙补偿 STEPGEN_MAXACCEL 应该比原本大100%。
STEPGEN_MAXVEL = 31.25
STEPGEN_MAXACCEL = 937.50
P = 1000.0
I = 0.0
D = 0.0
FF0 = 0.0
FF1 = 1.0
FF2 = 0.0
BIAS = 0.0
DEADBAND = 0.0
MAX_OUTPUT = 0.0
#这些以纳秒为单位
DIRSETUP   = 10000
DIRHOLD    = 10000
STEPLEN    = 5000
STEPSPACE  = 5000
STEP_SCALE = 200.0
MIN_LIMIT = -1000.0
MAX_LIMIT = 1000
HOME_OFFSET = 0.0
HOME_SEQUENCE = 1
#******************************************

#******************************************
[AXIS_A]
MAX_VELOCITY = 360
MAX_ACCELERATION = 1200.0
MIN_LIMIT = -9999.0
MAX_LIMIT = 9999.0

[JOINT_3]
TYPE = ANGULAR
HOME = 0.0
FERROR = 0.5
MIN_FERROR = 0.05
MAX_VELOCITY = 360
MAX_ACCELERATION = 1200.0
# 以下值应该比最大速度与最大加速度高25%
# 如果使用背隙补偿 STEPGEN_MAXACCEL 应该比原本大100%。
STEPGEN_MAXVEL = 450.00
STEPGEN_MAXACCEL = 1500.00
P = 1000.0
I = 0.0
D = 0.0
FF0 = 0.0
FF1 = 1.0
FF2 = 0.0
BIAS = 0.0
DEADBAND = 0.0
MAX_OUTPUT = 0.0
#这些以纳秒为单位
DIRSETUP   = 10000
DIRHOLD    = 10000
STEPLEN    = 5000
STEPSPACE  = 5000
STEP_SCALE = 27.7778
MIN_LIMIT = -9999.0
MAX_LIMIT = 9999.0
HOME_OFFSET = 0.0
HOME_SEQUENCE = 4
#******************************************

#******************************************
[AXIS_C]
MAX_VELOCITY = 360
MAX_ACCELERATION = 1200.0
MIN_LIMIT = -9999.0
MAX_LIMIT = 9999.0

[JOINT_4]
TYPE = ANGULAR
HOME = 0.0
FERROR = 0.5
MIN_FERROR = 0.05
MAX_VELOCITY = 360
MAX_ACCELERATION = 1200.0
# 以下值应该比最大速度与最大加速度高25%
# 如果使用背隙补偿 STEPGEN_MAXACCEL 应该比原本大100%。
STEPGEN_MAXVEL = 450.00
STEPGEN_MAXACCEL = 1500.00
P = 1000.0
I = 0.0
D = 0.0
FF0 = 0.0
FF1 = 1.0
FF2 = 0.0
BIAS = 0.0
DEADBAND = 0.0
MAX_OUTPUT = 0.0
#这些以纳秒为单位
DIRSETUP   = 10000
DIRHOLD    = 10000
STEPLEN    = 5000
STEPSPACE  = 5000
STEP_SCALE = 27.7778
MIN_LIMIT = -9999.0
MAX_LIMIT = 9999.0
HOME_OFFSET = 0.0
HOME_SEQUENCE = 5
#******************************************


[SPINDLE_0]
P = 0.0
I = 0.0
D = 0.0
FF0 = 1.0
FF1 = 0.0
FF2 = 0.0
BIAS = 0.0
DEADBAND = 0.0
MAX_OUTPUT = 24000.0
OUTPUT_SCALE = 24000
OUTPUT_MIN_LIMIT = -24000
OUTPUT_MAX_LIMIT = 24000

